name:                clay
version:             0.1.0.0
github:              "sullyj3/clay"
license:             BSD3
author:              "James Sully"
maintainer:          "sullyj3@gmail.com"
copyright:           "2018 James Sully"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sullyj3/clay#readme>

dependencies:
# - base >= 4.7 && < 5
- base >= 4.11 && < 5
- brick
- directory
- filepath
- logging
- microlens
- microlens-th
- text
- vector
- vty

library:
  source-dirs: src

executables:
  clay:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clay

tests:
  clay-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clay
